#ifndef _Q_CONFIG_H__
#define _Q_CONFIG_H__

#define UPDATE_FRQ 333
#define UPDATE_PERIOD_IN_US 3000
#define UDATE_PERIOD_IN_MS (float)UPDATE_PERIOD_IN_US/1000.0f
#define UPDATE_PERIOD_IN_SEC (float)UPDATE_PERIOD_IN_US/1000000.0f

#endif
