#ifndef TELEMETRY_H_
#define TELEMETRY_H_

#include "radio_channel.h"
#include "helpers.h"
#include "quaternion.h"


//TX mnemonic
#define ANGLES 0
#define PITCH 0
#define ROLL 1
#define YAW 2

#define ANGLES_PIDS 3
#define PICTH_PID 3
#define PROP_PITCH 3
#define INTEGR_PITCH 4
#define DIFF_PITCH 5

#define ROLL_PID 6
#define PROP_ROLL 6
#define INTEGR_ROLL 7
#define DIFF_ROLL 8

#define YAW_PID 9
#define PROP_YAW 9
#define INTEGR_YAW 10
#define DIFF_YAW 11

#define LOOP_TIME 12
#define ALTITUDE 13
#define ALTITUDE_VELOCITY 14

#define SONAR_DIST 15
#define SONAR_VELOCITY 16

#define COORDINATE_PIDS

#define COORDINATE_X_PID	(COORDINATE_PIDS)
#define PROP_COORDINATE_X	(COORDINATE_X_PID)
#define INTEGR_COORDINATE_X	(COORDINATE_X_PID + 1)
#define DIFF_COORDINATE_X	(COORDINATE_X_PID + 2)

#define COORDINATE_Y_PID	(COORDINATE_PIDS + 3)
#define PROP_COORDINATE_Y	(COORDINATE_Y_PID)
#define INTEGR_COORDINATE_Y	(COORDINATE_Y_PID + 1)
#define DIFF_COORDINATE_Y	(COORDINATE_Y_PID + 2)

#define COORDINATE_Z_PID	(COORDINATE_PIDS + 6)
#define PROP_COORDINATE_Z	(COORDINATE_Z_PID)
#define INTEGR_COORDINATE_Z	(COORDINATE_Z_PID + 1)
#define DIFF_COORDINATE_Z	(COORDINATE_Z_PID + 2)

#define RESERVED_CHANNAL0 100
#define RESERVED_CHANNAL1 (RESERVED_CHANNAL0 + 1)
#define RESERVED_CHANNAL2 (RESERVED_CHANNAL0 + 2)
#define RESERVED_CHANNAL3 (RESERVED_CHANNAL0 + 3)
#define RESERVED_CHANNAL4 (RESERVED_CHANNAL0 + 4)
#define RESERVED_CHANNAL5 (RESERVED_CHANNAL0 + 5)


#define GPS_LONGITUDE
#define GPS_LATITUDE
#define GPS_ACURACCY
#define GPS_SATELLITE_NUM

#define RELATIVE_X_POS
#define RELATIVE_Y_POS


void Telemetry_sendToPilot();


#endif
